//
// Generated file, do not edit! Created by nedtool 5.6 from packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>packet.msg:2</tt> by nedtool.
 * <pre>
 * packet pck
 * {
 *     unsigned int seq;
 *     unsigned short type;
 * }
 * </pre>
 */
class pck : public ::omnetpp::cPacket
{
  protected:
    unsigned int seq;
    unsigned short type;

  private:
    void copy(const pck& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const pck&);

  public:
    pck(const char *name=nullptr, short kind=0);
    pck(const pck& other);
    virtual ~pck();
    pck& operator=(const pck& other);
    virtual pck *dup() const override {return new pck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual unsigned int getSeq() const;
    virtual void setSeq(unsigned int seq);
    virtual unsigned short getType() const;
    virtual void setType(unsigned short type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const pck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, pck& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKET_M_H

